---
title: "SC_QualityControl"
output: html_document
---

### Library Read In

```{r}
#Seurat Core
library(Seurat)
#library(BPCells)
library(SeuratWrappers)
library(S4Vectors)

#non-Saitja QC libraries
library(DropletUtils)
library(scDblFinder)
library(SoupX)
library(SingleCellExperiment)

#Visualizations
library(ggplot2)
library(patchwork)
library(dplyr)
library(tidyverse)
```

```{r}
overall_dir <- "qc_images"
if(!dir.exists(dir)){
  dir.create(glue("./{overall_dir}"))
}
```

# GSE141445/Chen, O QC

```{r}
gse141445.obj <- readRDS("./sc_rds_files/gse141445.rds")
```

```{r}
#basic dimension reductions not set in stone because these are important
#For cluster annotation
tmp_obj <- gse141445.obj
tmp_obj <- NormalizeData(tmp_obj, verbose=F)
tmp_obj <- FindVariableFeatures(tmp_obj, nfeatures = 5000, verbose=F)
tmp_obj <- ScaleData(tmp_obj, verbose = FALSE)
tmp_obj <- RunPCA(tmp_obj, npcs=15, verbose = FALSE)
tmp_obj <- FindNeighbors(tmp_obj, dims = 1:15, verbose=F)
tmp_obj <- FindClusters(tmp_obj, resolution = 0.8, verbose =F)
sc <- setClusters(sc, setNames(as.character(temp_obj$seurat_clusters), colnames(temp_obj)))
```

Estimate Sparsity

```{r}
object <- gse141445.obj
rm(gse141445.obj)
```

```{r}
#Calculate Matrix Sparsity
total_element_wise_counts <- (sum(object@assays$RNA@layers$counts) > 0)
dims <- (nrow(object) * ncol(object))
sparsity <- 1 - (total_element_wise_counts / dims)

cat("Matrix sparsity:", round(sparsity * 100, 1), "%\n")

#UMI distribution - bimodal obviously
umi_counts <- colSums(object@assays$RNA@layers$counts)
cat("Median UMI per droplet:", median(umi_counts), "\n")
cat("Droplets with >500 UMI:", sum(umi_counts > 500) , 
    "(likely cells, will be validated by EmptyDrops)\n")
```

### Empty Droplet Detection

```{r}
ncol(object)
```

Need to write write description of the empty Droplets functions.

```{r}
emptyDrops_wrapr <- function(rna_mat, object) {
  #use a local variable to save the original matrix in here
  original_mat <- rna_mat
  
  initial_cell_cnt <- dim(original_mat)[1]
  initial_gene_cnt <- dim(original_mat)[2]
  
  #start of tryCatch
  tryCatch(
    {
      set.seed(100)
      #lower: Droplets with <100 UMI assumed empty. Depending on the experiment this could change
      #niters: Iterations for specifying the number of iterations to use for the Monte Carlo p-value calculations.
      empty_report <- emptyDrops(
        m = rna_mat,
        lower = 100,
        niters = 10000,
        test.ambient = TRUE
      )
      
      #filtering results
      #Identify cell with FDR < 0.01
      is_cell <- empty_report$FDR < 0.01
      is_cell[is.na(is_cell)] <- FALSE # Treat NAs as empty (very low UMIs per drolet)
      validated_barcodes <- colnames(object)[is_cell] # filtering by validated cells
      
      
      cat("Droplets tested:", ncol(object), "\n")
      cat("Cells called:", sum(is_cell), 
          "(", round(sum(is_cell)/ncol(object)*100, 1), "%)\n")
      cat("Empty droplets removed:", sum(!is_cell), 
          "(", round(sum(!is_cell)/ncol(object)*100, 1), "%)\n")
      
      
      #filtering the Seurat Object by the validated BardCodes
      save_raw_counts <- original_mat
      
      new_object <- subset(object, cells = validated_barcodes)
      
      cat("After Empty Drops:", ncol(new_object), "cells retained\n")
      
      
      return(list(empty_droplets, new_object))
    },
    #tryCatch error function will return the original matrix
    #This part is necessary because the author of the
    error = function(e) {
      message("Matrix Already Filtered by CellRanger")
    }#end of error bracket
      
  )# end of tryCatch
    
  
}# end of wrapr function
```

```{r}
empty_results <- emptyDrops_wrapr(object@assays$RNA@layers$counts, object)

```

```{r}

```
